### ISSUE TITLE
Minimal exe project template

### ISSUE THREAD

**Issue by martinboers** [PLCnext/PLCnext_CLI_Templates#2]
It would be useful to have a template for a minimal exe project, perhaps something that prints "Hello World" to stdout.

**Comment by martinboers** [comment]
An example of this type of template is described in a Makers Blog post on the PLCnext Community website:

https://www.plcnext-community.net/makersblog/plcnext-cli-templates/

**Comment by mluhmann** [comment]
Thanks Martin. Closing this issue for now. More documentation will follow.
